#**Creating dimensional array**

In [1]:
import numpy as np
x = [[0,1,2],[3,4,5],[6,7,8]]
arr = np.array(x)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#**zeros() function & ones() function**

In [2]:
arr1 = np.zeros((5,5))
print(arr1)
arr2 = np.ones((5,5))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#**copy() function**

In [3]:
a = np.array([1,2,3,4])
c = a.copy()
print(c)
c[0] = 0
print(c)
# one's the copy the value and then can't be change
a[1] = 0
print(c)

[1 2 3 4]
[0 2 3 4]
[0 2 3 4]


#**arange() function**

In [4]:
array = np.arange(1,30,2)
print(array)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


#**linspace & mod()-Modulation**

In [5]:
vector = np.linspace(0, 20, 5)
print(vector)
h = np.mod(26,5)
print("h = ",h)

[ 0.  5. 10. 15. 20.]
h =  1


#**eye function is used for identical matrix**

In [6]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#**dot matrix used for same size of the multiple using matrix**

In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,45],[7,8]])
c = np.dot(a,b)
print(a.shape)
print(c)
print(a)
print(b)

(2, 2)
[[ 17  61]
 [ 37 167]]
[[1 2]
 [3 4]]
[[ 3 45]
 [ 7  8]]


#**Numpy function**
1.universal function

In [8]:
sqrt = np.sqrt([1,4,9])
add = np.add(2,3)
print(add)

log = np.log(1)
print(log)

#Trignometric functions
sin = np.sin(60)
print(sin)

cos = np.cos(0)
print(cos)

hypot = np.hypot(4,4)
print(hypot)

bitwise_and = np.bitwise_and(3,8)
print(bitwise_and)

5
0.0
-0.3048106211022167
1.0
5.656854249492381
0


#**aggregate function**
max, min, sum, mean, std

In [9]:
sum = np.sum(a)
print(sum)

min = np.min(a)
print(min)

max = np.max(a)
print(max)

10
1
4


#**logic function**
all, any, iscomplex, isreal.


logical_or,
logical_not,
logical_xor,
logical_and.

In [10]:
a = np.array([1, 78, 23, 12, 90, 10,45, 56])
ind = np.array([[3,5],[2,6]])
print(a[ind])

print(a[ind[1,:]])

[[12 10]
 [23 45]]
[23 45]


In [11]:
b = np.nditer(a[0])
print(b)

##**Array manipulation**
changing array shape , transpose like operation

In [12]:
x = [1,2,3,6,4,5]
arr = np.array(x)
arr1 = np.reshape(arr,(3,2))
print(arr1)

[[1 2]
 [3 6]
 [4 5]]


In [13]:
b = arr1.ravel()
print(b)

print(type(b))

[1 2 3 6 4 5]
<class 'numpy.ndarray'>


In [14]:
print(arr1)
a = arr1.T
print(a)

[[1 2]
 [3 6]
 [4 5]]
[[1 3 4]
 [2 6 5]]


In [15]:
x = arr1.reshape(2,3)
print(x)

y = x.reshape(-1)
print(x)

z = x.flatten()
print(z)

x = np.array([[[0],[1],[2]]])
print(x.shape)
a = np.squeeze(x, axis = 0)
print(a)

[[1 2 3]
 [6 4 5]]
[[1 2 3]
 [6 4 5]]
[1 2 3 6 4 5]
(1, 3, 1)
[[0]
 [1]
 [2]]


#**Concatenate**

Concatenate is used for two matrix or string etc...

join the 2 variables, list, array

In [16]:
a = np.array([[1,3],[3,4]])
b = np.array([[2,3],[6,7]])
print("Array1: ")
print(a)
print("Array2: ")
print(b)
con = np.concatenate((a,b), axis = 1)
print("Concatenate: ")
print(con)

Array1: 
[[1 3]
 [3 4]]
Array2: 
[[2 3]
 [6 7]]
Concatenate: 
[[1 3 2 3]
 [3 4 6 7]]


#**Stack**

Stack is used for join the sequence of arrays alone a new axis

In [17]:
stack = np.stack((a,b))
print(stack)


[[[1 3]
  [3 4]]

 [[2 3]
  [6 7]]]


#**Horizantal stack, Vertical stack**


In [18]:
a = np.array((91,2,4))
b = np.array((3,4,6))
c = np.hstack((a,b))
d = np.vstack((a,b))
print(c)
print(d)


[91  2  4  3  4  6]
[[91  2  4]
 [ 3  4  6]]


#**Splitting arrays**

1.horizantal split
2.vertical split

In [19]:
a = np.arange(16).reshape((4,4))
print(a)

[b,c] = np.split(a,2, axis = 1)
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [20]:
arr = np.hsplit(a,2)
arr

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
arr1 = np.vsplit(a,2)
print(arr1)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


#**File handling**
file handling is nothing but used for save and load. It is used for open the file and read or write.

In [22]:
x = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(x)
arr = np.save("file.npy",a)

arr1 = np.savetxt("fil.txt",a)
b = np.genfromtxt("fil.txt",arr1)
c = np.load("file.npy",arr)
print(b)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#**Pandas library**
Meaning of the pandas as the panel and data. Data preprocessing, Data cleaning, Data transformation. Pandas open source library that provides high performance
data structures to perform efficient data manipulation and analysis in python.
Further manipulation process of the sampling, Data cleaning, Data transformation, Data wrangling, Data analysis.


In [23]:
import pandas as pd


#**Pandas Series**
One dimensional labelled structure

In [24]:
#data = {'a':10, "b":20, "c":30}
data = [1,2,3,4]
series = pd.Series(data, index = ['a', 'b', 'c','d'])
print(series)


a    1
b    2
c    3
d    4
dtype: int64


#**Pandas DataFrame**
Dataframe is two-dimensional labelled data sturctures with columns of different types:

In [25]:
data = [{'a':10, "b":20, "c":30, "d":40},{'a':1, "b":2, "c":3}]

dataframe = pd.DataFrame(data, index = ['a', 'b'])
print(dataframe)


    a   b   c     d
a  10  20  30  40.0
b   1   2   3   NaN
