#**Numpy concept**

In [5]:
import numpy as np
x = [[0, 1, 2],[3, 4, 5], [6, 7, 8]]
arr = np.array(x)
print(arr)
type(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


numpy.ndarray

##**Zeros  & Ones function**

In [8]:
arr1 = np.zeros((5,5))
print(arr1)
arr2 = np.ones((3,3))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##**Copy, Arange, linspace, lipher, eye, dot**

In [24]:
#Copy
a = np.array([1,2,3,4,5])
c = a.copy()
print(c)
del(c)


[1 2 3 4 5]


In [36]:
#Arange
a = np.arange(1,31,2)
print(a, "\n")
#Linspace
c = np.linspace(2,4)
print(c)
type(c)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29] 

[2.         2.04081633 2.08163265 2.12244898 2.16326531 2.20408163
 2.24489796 2.28571429 2.32653061 2.36734694 2.40816327 2.44897959
 2.48979592 2.53061224 2.57142857 2.6122449  2.65306122 2.69387755
 2.73469388 2.7755102  2.81632653 2.85714286 2.89795918 2.93877551
 2.97959184 3.02040816 3.06122449 3.10204082 3.14285714 3.18367347
 3.2244898  3.26530612 3.30612245 3.34693878 3.3877551  3.42857143
 3.46938776 3.51020408 3.55102041 3.59183673 3.63265306 3.67346939
 3.71428571 3.75510204 3.79591837 3.83673469 3.87755102 3.91836735
 3.95918367 4.        ]


numpy.ndarray

In [112]:
#Mod()
arr = np.mod(9,4)
print(arr)
arr1 = np.eye(2,3)
print("eye:",arr1,"\n")
arr2 = np.char.capitalize("PYTHON")
arr_2 = np.char.lower(arr2)
arr_3 = np.char.upper(arr_2)
print(arr_2)
print(arr_3)
print("Character capitalize:",arr2, "\n")
arr3 = np.char.add("python", " is programming language")
print("concatenation:",arr3,"\n")
arr4 = np.char.multiply("Naveen ",3)
print("Multiply:",arr4, "\n")
arr5 = np.char.mod("Naveen", 3)
print("modulation:", arr5,"\n")

arr6 = np.char.center("Naveen", 2,fillchar ="e")
print("Center function:",arr6, "\n")
arr7 = np.char.join("naveen", "123")
print("join:",arr7, "\n")
arr8 = np.char.ljust("naveen",width = 4)
print("ljust:", arr8, "\n")
arr9 = np.char.swapcase("WhATEVER FINE")
print("Swapcase:",arr9,"\n")
arr10 = np.char.lstrip(np.array(["naveen","dinesh","umamaheshwari","vellingiri","avignesh"]),"n")
print("lstrip:", arr10, "\n")


1
eye: [[1. 0. 0.]
 [0. 1. 0.]] 

python
PYTHON
Character capitalize: Python 

concatenation: python is programming language 

Multiply: Naveen Naveen Naveen  

modulation: Naveen 

Center function: Na 

join: 1naveen2naveen3 

ljust: nave 

Swapcase: wHatever fine 

lstrip: ['aveen' 'dinesh' 'umamaheshwari' 'vellingiri' 'avignesh'] 



In [171]:
arr11 = np.char.partition("naveen",["n",'a',"v","e","e","n"])
print("Partition:", arr11, "\n")
c = np.array(["A success is kee","kee is another word is lossing"])
arr12 = np.char.replace(c,"kee", "key")
print(c)
print("replace:",arr12, '\n')
arr13 = np.char.ljust("naveen",width = 7,fillchar = "n")
print("rjust:", arr13, "\n")
arr14 = np.char.partition("n","f")
print("rpartition:", arr14, "\n")
a = np.array("naveen is bad boy")
arr15 = np.char.rsplit(a,"n" )
print("splitlines:", arr15, "\n")

Partition: [['' 'n' 'aveen']
 ['n' 'a' 'veen']
 ['na' 'v' 'een']
 ['nav' 'e' 'en']
 ['nav' 'e' 'en']
 ['' 'n' 'aveen']] 

['A success is kee' 'kee is another word is lossing']
replace: ['A success is key' 'key is another word is lossing'] 

rjust: naveenn 

rpartition: ['n' '' ''] 

splitlines: ['', 'avee', ' is bad boy'] 

